version: 0.2
phases:
  install:
    commands:
      - echo Installing Node 14...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Testing...
      - npm run test
      - echo Building...
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
#phases:
#  pre_build:
#    commands:
#      #installs dependencies into the node_modules/ directory
#      - npm install
#  build:
#    commands:
#      - echo Build started on `date`
#      - echo Compiling
#      - npm run build
#  post_build:
#    commands:
#      - echo Build completed on `date`
#  # Include only the files required for your application to run.
#artifacts:
#  files:
#    - public/**/*
#    - src/**/*
#    - package.json
#    - appspec.yml
#    - scripts/**/*
