version: '3'

services:

  # App container
  app:
    container_name: sportfolios_app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/sportfolios'
      - '/sportfolios/node_modules'
    ports:
      - 3000:3000