version: '3'
services:
  # API container
  api:
    container_name: sportfolios_api_dev
    build:
      context: .
      dockerfile: Dockerfile.api
      network: 'host'
    ports:
      - 1337:1337
    volumes:
      - '.:/sportfolios'
      - '/sportfolios/node_modules'
    # make container listen to file changes
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
  db:
    container_name: sportfolios_db_dev
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      # persist data even if container shuts down
      - ../sportfolios-data/postgres-data:/var/lib/postgresql/data/
    environment:
      # default user is postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sportfolios_api_dev
