version: '3'

services:

  # API container
  api:  
    container_name: sportfolios_api
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - '.:/sportfolios'
      - '/sportfolios/node_modules'
    ports:
      - 1337:1337
    # allow container to interact with localhost (for localhost database in dev)
    network_mode: 'host'  

  # App container
  app:
    container_name: sportfolios_app_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/sportfolios'
      - '/sportfolios/node_modules'
    ports:
      - 3000:3000