# Use proper node image
FROM node:14.18

# Directory to use in container
WORKDIR /sportfolios

ENV PATH /sportfolios/node_modules/.bin:$PATH

# Copy file into container
COPY . ./

# Install modules into container
RUN npm install && npm cache clean --force

# Start the api
CMD npm run webserver --trace-warnings
