name: Docker Image CI

on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: sportfoliosapp/sportfolios-stable
      - name: Build and push Docker image staging
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
          repository: sportfoliosapp/sportfolios-stable
          context: .
          push: true
          tags: sportfoliosapp/sportfolios-stable:staging
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.staging
      - name: Build and push Docker image prod
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
          repository: sportfoliosapp/sportfolios-stable
          context: .
          push: true
          tags: sportfoliosapp/sportfolios-stable:production
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.production
